name: VellaSDK
rust:
  directory: ./vella-sdk
  manifestPath: Cargo.toml
ios:
    directory: ios
    targets:
    - aarch64-apple-ios
    - aarch64-apple-ios-sim
    - x86_64-apple-ios
    frameworkName: ios/VellaSDK
