name: VellaSDK
rust:
  directory: ./vella-sdk
  manifestPath: Cargo.toml
ios:
    directory: ios
    native_bindings_dir: swift
    targets:
    - aarch64-apple-ios
    - aarch64-apple-ios-sim
    frameworkName: ios/VellaSDK
