// Generated by uniffi-bindgen-react-native
#include "vella-sdk.h"
#include "generated/vella_sdk.hpp"

namespace vellasdk {
	using namespace facebook;

	uint8_t installRustCrate(jsi::Runtime &runtime, std::shared_ptr<react::CallInvoker> callInvoker) {
		NativeVellaSdk::registerModule(runtime, callInvoker);
		return true;
	}

	uint8_t cleanupRustCrate(jsi::Runtime &runtime) {
		return false;
	}
}