// Generated by uniffi-bindgen-react-native
#ifdef __cplusplus
#import "vella-sdk.h"
#endif

#ifdef RCT_NEW_ARCH_ENABLED
#import "RNVellaSdkSpec.h"

@interface VellaSdk : NSObject <NativeVellaSdkSpec>
#else
#import <React/RCTBridgeModule.h>

@interface VellaSdk : NSObject <RCTBridgeModule>
#endif

@end