// Generated by uniffi-bindgen-react-native
import installer from './NativeVellaSdk';

// Register the rust crate with Hermes
// - the boolean flag ensures this loads exactly once, even if the JS
//   code is reloaded (e.g. during development with metro).
let rustInstalled = false;
if (!rustInstalled) {
  installer.installRustCrate();
  rustInstalled = true;
}

// Export the generated bindings to the app.
export * from './generated/schemaorg_rs';
export * from './generated/vella_sdk';

// Now import the bindings so we can:
// - intialize them
// - export them as namespaced objects as the default export.
import * as schemaorg_rs from './generated/schemaorg_rs';
import * as vella_sdk from './generated/vella_sdk';

// Initialize the generated bindings: mostly checksums, but also callbacks.
// - the boolean flag ensures this loads exactly once, even if the JS code
//   is reloaded (e.g. during development with metro).
let initialized = false;
if (!initialized) {
  schemaorg_rs.default.initialize();
  vella_sdk.default.initialize();
  initialized = true;
}

// Export the crates as individually namespaced objects.
export default {
  schemaorg_rs,
  vella_sdk,
};
